default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: 5
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default
  database: rails_experiment_development

test:
  <<: *default
  database: restful_api_rails_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: restful_api_rails_production
